### ISSUE TITLE
Yearly sensors unavailable as of 7/12

### ISSUE THREAD

**Issue by tmh88** [HandyHat/ha-hildebrandglow-dcc#274]
I noticed yesterday yearly elec and gas sensors were unavailable. Rebooted HA and I got one reading however checked again this morning and sensors showing as unavailable again. All others still reading. Just yearly sensors seem to be the problem.

**Comment by alexhildebrand** [comment]
Hello @adam-cobb, @tmh88,
the issue was relating to the Glowmarkt API and should now be resolved.

**Comment by adam-cobb** [comment]
Thanks @alexhildebrand, I'm still not seeing data but I'll give a bit and see if it comes back, appreciate the update thanks 🙂

**Comment by viking2010** [comment]
Yeah I'm still seeing the same issue unfortunately. Will give it time and see if anything changes.

**Comment by neilmartin83** [comment]
Nothing from my daily or yearly sensors since 12:55pm today...  the Bright app seems to be having problems refreshing data as well, so guessing an API issue at their end.

**Comment by darkmatter24** [comment]
Seeing the same here, loads of 500 errors in the logs and been getting only 1 or 2 updates a day for the yearly sensors for the last couple of days

**Comment by thorrrr** [comment]
Same here Bright App fine i have tried reloading the HA Integration but noting.
Looks like the API is not fixed or connecting

**Comment by Seaniau** [comment]
Today I've noticed that since having this problem, which has now resolved itself for me; The Yearly sensors are only updating once per day, adding the previous day's usage. I've switched to using the Daily sensors in the Energy Dashboard now and this appears to work as expected with regular updates.

**Comment by thorrrr** [comment]
> Try reloading the integration. All the entities are working for me, but I had to reload the integration a few days ago to get the consumption entities back, which took some time to update from “unavailable”.

HI
I have tried reloading it a few times and a full reboot of HA makes no difference to mine both are broke day and yearly

**Comment by graham33** [comment]
In my case the yearly consumption sensor has a valid value but doesn't seem to ever change (although I've only had the integration installed a couple of days now). Switching to the daily sensor worked fine for me.

**Comment by tmh88** [comment]
Still got issues with yearly sensors, daily sensors seem abit more reliable! Are there any issues with switching from yearly to daily sensors for the energy dashboard? The documentation recommends using the yearly sensor? Thanks

**Comment by HandyHat** [comment]
The yearly sensors have been removed as of v1.0.0.
Please use the daily sensors in the energy dashboard, as they now contain the missing 30 minutes at the end of each day.
